### ISSUE TITLE
error during File Provisiner

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#13]
getting below error message 

OS : ubuntu16.04.03-x64-desktop
virtualbox:virtualbox-5.2_5.2.6-120293~Ubuntu~xenial_amd64.deb
vagrant:vagrant_2.0.1_x86_64.deb

k8s-master-2: Installing master...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /root/kubernetes_the_easy_way/output/k8s-worker-1.kubeconfig must exist
* File upload source file /root/kubernetes_the_easy_way/output/kube-proxy.kubeconfig must exist

**Comment by hoeghh** [comment]
What is the content of the folder output ?

**Comment by vikasgubbi** [comment]
This is what are you asking about

root@kubernetes:~/kubernetes_the_easy_way/output# ls -ltr
total 12
-rw-r--r-- 1 root root 466 Jan 23 02:44 README.md
-rw-r--r-- 1 root root 272 Jan 23 02:54 hosts
-rw-r--r-- 1 root root 240 Jan 23 02:54 encryption-config.yaml
root@kubernetes:~/kubernetes_the_easy_way/output# more hosts
192.168.50.4 k8s-loadbalancer
192.168.50.20 k8s-master
192.168.50.11 k8s-etcd-1
192.168.50.12 k8s-etcd-2
192.168.50.21 k8s-master-1
192.168.50.22 k8s-master-2
192.168.50.31 k8s-worker-1
192.168.50.32 k8s-worker-2
192.168.50.33 k8s-worker-3
192.168.50.5 k8s-loadbalancer-1

**Comment by hoeghh** [comment]
What is the content of logs/kube-configs.log ?

**Comment by vikasgubbi** [comment]
It was a permission issue with one the file in scripts folder.changed the permission , rerun install.sh script. It went further with the log (vagrant-provition.log) output at the end

==> k8s-loadbalancer-1: flag to force provisioning. Provisioners marked to run a
lways will still run.

with that install.sh script got terminated.Is this as expected behaviour.

**Comment by hoeghh** [comment]
When the install.sh finished you should have the machines defined in the file config. 
This is still work in progress. As stated in the README.md only etcd is done (and certificates). Im working on the masters right now (almost done). 

So, did the install.sh finish by itself? And did you get the vm's defined in config?

**Comment by vikasgubbi** [comment]
Yes, install.sh script finish by itself.

config file output
------------------------------------------------------------
export ETCD_COUNT=2
export ETCD_CPU=1
export ETCD_MEM=512
export MASTER_COUNT=2
export MASTER_CPU=1
export MASTER_MEM=1024
export WORKER_COUNT=3
export WORKER_CPU=2
export WORKER_MEM=2048
export LOADBALANCER_COUNT=1
export LOADBALANCER_CPU=1
export LOADBALANCER_MEM=512

**Comment by hoeghh** [comment]
So the problem is solved by adding x permissions to the file? If so, then lets close this issue.

**Comment by vikasgubbi** [comment]
yes please
