### ISSUE TITLE
Configuring kubectl for Remote Access

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#14]
Hi,

How to Configuring kubectl for Remote Access .Please provide steps for the same.

Regards,
Vikas

**Comment by hoeghh** [comment]
Thats a good idea. I will do that once im done with the cluster setup scripts.

**Comment by vikasgubbi** [comment]
Please let me know when you will upload to github.

**Comment by hoeghh** [comment]
I will make a comment here when done.

**Comment by hoeghh** [comment]
@vikasgubbi I have updated the readme. You should re-run the install.sh script to get workers and masters generated again. I still need to implement loadbalancers, but now you can actually connect and use the cluster. Cluster networking is still missing though. 

But that should be something like this, when you have kubectl running:
```
export kubever=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
```

**Comment by hoeghh** [comment]
If it works, then please close the issue. Otherwise let me know what's wrong.

**Comment by hoeghh** [comment]
After more then a month inactivity, im closing the issue. Please reopen if the problem persist.
I have tested my changes, and they seems to work.
