### ISSUE TITLE
Pods are ContainerCreating state for long time

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#22]
Pods are ContainerCreating state for long time, please advice
---------------------------------------------------------------------------------------------
kubectl describe pods
Name:           kubernetes-dashboard-64b6f585dd-mctwj
Namespace:      default
Node:           k8s-worker-2/192.168.50.32
Start Time:     Fri, 02 Feb 2018 17:26:57 +0530
Labels:         pod-template-hash=2062914188
                run=kubernetes-dashboard
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/kubernetes-dashboard-64b6f585dd
Containers:
  kubernetes-dashboard:
    Container ID:   
    Image:          k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.2
    Image ID:       
    Port:           8888/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8nn45 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-8nn45:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8nn45
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age   From                   Message
  ----     ------                  ----  ----                   -------
  Warning  FailedCreatePodSandBox  59m   kubelet, k8s-worker-2  Failed create pod sandbox.
  Normal   SuccessfulMountVolume   59m   kubelet, k8s-worker-2  MountVolume.SetUp succeeded for volume "default-token-8nn45"
  Normal   SuccessfulMountVolume   59m   kubelet, k8s-worker-2  MountVolume.SetUp succeeded for volume "default-token-8nn45"
  Warning  FailedCreatePodSandBox  59m   kubelet, k8s-worker-2  Failed create pod sandbox.
  Normal   SuccessfulMountVolume   59m   kubelet, k8s-worker-2  MountVolume.SetUp succeeded for volume "default-token-8nn45"
  Warning  FailedCreatePodSandBox  59m   kubelet, k8s-worker-2  Failed create pod sandbox.

**Comment by hoeghh** [comment]
Yes I saw it. I have made an issue in Kelsey's repo kubernetes the hard way.

**Comment by hoeghh** [comment]
I have created a pastbin with all logs on this error:

https://pastebin.com/GW2kwcLG

**Comment by vikasgubbi** [comment]
Any plans to change LXC to Docker as of now.

**Comment by hoeghh** [comment]
Yes i will change to docker from containerd
I just need to get some time for it 😊

**Comment by hoeghh** [comment]
Hi,

Could you try and to a ./destroy.sh, git pull and try again with ./install.sh
I think i have it working now. @vikasgubbi

**Comment by vikasgubbi** [comment]
Hi,

install.sh struck at " Installing loadbalancer"  for more than 80 minutes. vagrant-provition.log output below
----------------------------------------------------------------------------------------------
==> k8s-loadbalancer-1: Mounting shared folders...
    k8s-loadbalancer-1: /vagrant => /root/kubernetes_the_easy_way
==> k8s-loadbalancer-1: Running provisioner: file...
==> k8s-loadbalancer-1: Running provisioner: file...
==> k8s-loadbalancer-1: Running provisioner: shell...
    k8s-loadbalancer-1: Running: /tmp/vagrant-shell20180305-9802-ahgkwt.sh
    k8s-loadbalancer-1: Installing loadbalancer...
-----------------------------------------------------------------------------------------------
logs folder contents

-rw-r--r--. 1 root root  2716 Mar  5 00:08 cert.log
-rw-r--r--. 1 root root     0 Mar  5 00:08 data-encryption.log
-rw-r--r--. 1 root root   477 Mar  5 00:08 kube-configs.log
-rw-r--r--. 1 root root 75861 Mar  5 00:32 vagrant-provition.log
-rw-r--r--. 1 root root   148 Mar  5 00:32 kubedeploy.log
-rw-r--r--. 1 root root   120 Mar  5 00:32 kubedns.log
-rw-r--r--. 1 root root   149 Mar  5 00:32 post_deploy.log
-rw-r--r--. 1 root root   193 Mar  5 00:32 weavenet.log
--------------------------------------------------------------------------------------------
Regards,Vikas

**Comment by hoeghh** [comment]
I added some extra echo to the script that installs the loadbalacer. I pushed it around the time you can it. It is strange that you don't get more output, if it's the newest commit. 

Could you check that you have the newest ? It should say something like downloading binaries...

**Comment by hoeghh** [comment]
And please edit the config file and set the number of load balancers to 1 only.

Remember to destroy before trying again.

**Comment by vikasgubbi** [comment]
Hi,

I modified it before running install.sh. My config file 

export ETCD_COUNT=1
export ETCD_CPU=1
export ETCD_MEM=512
export MASTER_COUNT=1
export MASTER_CPU=1
export MASTER_MEM=1024
export WORKER_COUNT=2
export WORKER_CPU=2
export WORKER_MEM=1048
export LOADBALANCER_COUNT=1
export LOADBALANCER_CPU=1
export LOADBALANCER_MEM=512

Regards,Vikas

**Comment by hoeghh** [comment]
Did you do a git pull before trying?

After printing the last line you get, it should print out another line. It seems strange that that would fail a simple echo command. 

The file scripts/install_loadbalancer.sh is not empty right?

**Comment by vikasgubbi** [comment]
Hi,

No its not empty

ls -ltr
total 44
-rwxrwxrwx. 1 root root 1850 Mar  4 23:50 generate_kube_config.sh
-rwxrwxrwx. 1 root root  810 Mar  4 23:50 generate_hosts.sh
-rwxrwxrwx. 1 root root  314 Mar  4 23:50 generated_data_encryption.sh
-rwxrwxrwx. 1 root root 3526 Mar  4 23:50 generate_certs.sh
-rwxrwxrwx. 1 root root 4010 Mar  4 23:50 install-worker.sh
-rwxrwxrwx. 1 root root 5001 Mar  4 23:50 install-master.sh
-rwxrwxrwx. 1 root root   34 Mar  4 23:50 install-loadbalancer.sh
-rwxrwxrwx. 1 root root 1966 Mar  4 23:50 install-etcd.sh
-rwxrwxrwx. 1 root root 1915 Mar  4 23:50 install-corosync.sh
-rwxrwxrwx. 1 root root 1167 Mar  4 23:50 post_deploy.sh
[root@jenkins scripts]# more install-loadbalancer.sh
echo "Installing loadbalancer..."

Regards,Vikas

**Comment by hoeghh** [comment]
The file should have many lines of code. 

Please do a git pull and check that the file has grown.

**Comment by vikasgubbi** [comment]
Hi,

Getting below mentioned message in vagrant-provition.log file

 k8s-loadbalancer-1: Unable to connect to the server: dial tcp 192.168.50.20:6443: getsockopt: no route to host
    k8s-loadbalancer-1: Getting token and ca.crt for Traefik from api-server...
    k8s-loadbalancer-1: the server doesn't have a resource type "sa"
    k8s-loadbalancer-1: Unable to connect to the server: dial tcp 192.168.50.20:6443: getsockopt: no route to host
    k8s-loadbalancer-1: Unable to connect to the server: dial tcp 192.168.50.20:6443: getsockopt: no route to host
    k8s-loadbalancer-1: Created symlink from /etc/systemd/system/multi-user.target.wants/traefik.service to /etc/systemd/system/traefik.service.
    k8s-loadbalancer-1: Redirecting to /bin/systemctl start traefik.service
    k8s-loadbalancer-1: Cleaning up...


Regards,Vikas

**Comment by hoeghh** [comment]
Could you check if there was any errors on the master machines in the log? Its seems that the floating ip (192.168.50.20) is not created.

Its also in the vagrant-provition.log file (search for master-1).

Did you do a ./destroy.sh before running ./install.sh ? If not, then try ./destroy.sh and then ./install.sh again.

**Comment by hoeghh** [comment]
I found the error. I had removed a line in the Vagrantfile that i shouldnt. 
Im fixing it now, and adding HA to the loadbalancers.

I make a post here when i have pushed the changes.

**Comment by hoeghh** [comment]
Ok, so i've fixed the problem with Corosync and i have tested the cluster with two masters and two loadbalancers.

Please test again, and see if it works.
I it works, you should be able to get the traefik dashboard at http://192.168.50.4:8080

Fixed with bf50f0bd9c8c5290c0157bb4f4fc80dbb4214ed5

If it works, please comment and close the issue :)

**Comment by vikasgubbi** [comment]
Hi,

Load Balancer successfully installed,closing the ticket.

Regards,Vikas
