### ISSUE TITLE
 unable to do ssh to the machine

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#30]
Hi,

$vagrant ssh k8s-master-1
The machine with the name 'k8s-master-1' was not found configured for
this Vagrant environment.

 unable to do ssh to the machine.

Regards,Vikas

**Comment by hoeghh** [comment]
You need to source the config file first

source config
vagrant ssh [machine]

**Comment by hoeghh** [comment]
I've added it to the new documentation im building.

[Documentation](../blob/master/docs/README.md)
