### ISSUE TITLE
password for vagrant boxes to do scp

### ISSUE THREAD

**Issue by vikasgubbi** [hoeghh/kubernetes_the_easy_way#38]
Hi,

Please provide password for vagrant boxes to do scp.

Regards,Vikas

**Comment by hoeghh** [comment]
You need to source to config file first. 

source config
vagrant scp ....
Or
vagrant ssh [machinename]

**Comment by vikasgubbi** [comment]
Hi,

really sorry for the silly questions.

Regards,Vikas

**Comment by hoeghh** [comment]
They are not silly. They are good questions. I will update the README.md to include instructions on how to get inside the machines.
